model_type: 10
model_name: ODDDeepTTC_RRF

marker: exp_odd_deepttc_ODD

cuda_name: cuda:0

work_dir: K35_10epoch_wasserstein_top80_down20_remainRawFusion
batch_size: 
  train: 256 
  val: 256
  test: 256 
lr: 0.000001
num_epoch: 10
log_interval: 50
seed: 171

dataset_name: GDSCv2

dataset_type: 
  scale: 1
  select_type: many_lh
  # r3  three datasets are all random, and not mixed
  # m2r train and val datasets are mixed, test dataset is random
  # dataset_path: /home/lk/project/NCI60_dataset/normal_format
  # dataset_path: /home/lk/project/NCI60_dataset/selected
  dataset_path: /home/lk/Data/GDSC2_dataset/drug_classed
  train: [1]
  val: 0.2
  test: "Cytarabine.pt"
  K: 35

model:
  
  drug_module: 
    module_name: 
      - Transformer
    input_drug_feature_dim: 2586
    output_drug_feature_dim: 128
    layer_num: 8

    gnn_layers:  
      embed_dim: 128
      intermediate_dim: 512
      output: 256
      attention_probs_dropout: 0.1
      hidden_dropout: 0.1
      head: 8

    graph_pooling: max
    dropout: 0.1

  cell_module: 
    module_name: MLP
    input_cell_feature_dim: 735
    output_cell_feature_dim: 256

    linear_layers:
      - 
        operate_name: linear
        param:
          - 735
          - 1024
      - 
        operate_name: relu
      - 
        operate_name: linear
        param:
          - 1024
          - 256
      - 
        operate_name: relu
      - 
        operate_name: linear
        param:
          - 256
          - 64
      - 
        operate_name: relu
      - 
        operate_name: linear
        param:
          - 64
          - 256
      - 
        operate_name: relu


  fusion_module:

    module_name: MLP

    linear_layers:
      - 
        operate_name: linear
        param:
          - 384
          - 1024
      -
        operate_name: dropout
        param: 0.1
      - 
        operate_name: relu

      - 
        operate_name: linear
        param:
          - 1024
          - 1024
      -
        operate_name: dropout
        param: 0.1
      - 
        operate_name: relu

      - 
        operate_name: linear
        param:
          - 1024
          - 512
      -
        operate_name: dropout
        param: 0.1
      - 
        operate_name: relu

      - 
        operate_name: linear
        param:
          - 512
          - 1


    fusion_mode: concat
