model_type: 9
model_name: ODDGraTransDRP_RRF


marker: exp_odd_gratrans_ODD


cuda_name: cuda:0


work_dir: K35_100epoch_wasserstein_top100_top80_remainRawFusion


batch_size: 
  train: 256 
  val: 256
  test: 256 
lr: 0.000001
num_epoch: 100
log_interval: 50
seed: 171


dataset_name: NCI60

dataset_type: 
  scale: 1
  select_type: many_lh
  # r3  three datasets are all random, and not mixed
  # m2r train and val datasets are mixed, test dataset is random
  # dataset_path: /home/lk/project/NCI60_dataset/normal_format
  # dataset_path: /home/lk/project/NCI60_dataset/selected
  dataset_path: /home/lk/Data/NCI60_dataset/32310
  train: [1]
  val: 0.2
  test: "Cytarabine.pt"
  K: 35
    

model:
  
  drug_module: 
    input_drug_feature_dim: 90
    input_drug_edge_dim: 5
    use_drug_edge: False # False
    fc_1_dim: 1500
    fc_2_dim: 128
    dropout: 0.5
    transformer_dropout: 0.5

  cell_module: 
    module_name: Conv1d
    input_cell_feature_dim: 735
    fc_1_dim: 128
    layer_num: 3
    layer_hyperparameter:
      kernel_size:
        - 8
        - 8
        - 8
      maxpool1d: 
        - 3
        - 3 
        - 3
      cnn_channels:
        - 32
        - 64
        - 128


  fusion_module:
    fc_1_dim: 1024
    fc_2_dim: 128
    fc_3_dim: 1
    dropout: 0.5
    transformer_dropout: 0.5
    fusion_mode: concat
